package telas;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Time;
import modelo.Jogador;


public class ListaTimes extends javax.swing.JDialog {

    private ArrayList<Time> lista;
    private ArrayList<Jogador> listaj;


    public ListaTimes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();                
    }

    public ListaTimes(java.awt.Frame parent, boolean modal,
                ArrayList<Time> listati) {
        super(parent, modal);
        initComponents();
        lista = listati;
        lista();
    }
    
    public ListaTimes(java.awt.Frame parent, boolean modal,
                ArrayList<Time> listati,
                ArrayList<Jogador> listajog) {
        super(parent, modal);
        initComponents();
        lista = listati;
        listaj = listajog;
        lista();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLista = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btInserir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btInserirJogadorElenco = new javax.swing.JButton();
        btMostrarJogadorElenco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jtLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Apelido", "Escudo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtLista);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listagem de Times");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_form_add.png"))); // NOI18N
        btInserir.setToolTipText("Inserir novo registro");
        btInserir.setFocusable(false);
        btInserir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInserir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        jToolBar1.add(btInserir);

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        btAlterar.setToolTipText("Alterar registro selecionado");
        btAlterar.setFocusable(false);
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jToolBar1.add(btAlterar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_delete.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir registro selecionado");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btExcluir);

        btInserirJogadorElenco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/basket_put.png"))); // NOI18N
        btInserirJogadorElenco.setToolTipText("Inserir Jogador no Elenco");
        btInserirJogadorElenco.setFocusable(false);
        btInserirJogadorElenco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInserirJogadorElenco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btInserirJogadorElenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirJogadorElencoActionPerformed(evt);
            }
        });
        jToolBar1.add(btInserirJogadorElenco);

        btMostrarJogadorElenco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/basket_go.png"))); // NOI18N
        btMostrarJogadorElenco.setToolTipText("Mostrar Jogadores do Elenco");
        btMostrarJogadorElenco.setFocusable(false);
        btMostrarJogadorElenco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMostrarJogadorElenco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMostrarJogadorElenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarJogadorElencoActionPerformed(evt);
            }
        });
        jToolBar1.add(btMostrarJogadorElenco);

        jLabel1.setText("                        ");
        jToolBar1.add(jLabel1);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/note_go.png"))); // NOI18N
        btSair.setToolTipText("Fechar janela e voltar ao menu principal");
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btSair);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(416, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (jtLista.getSelectedRowCount() > 0) {
            ArrayList<Time> paraExcluir = new ArrayList<Time>();
            for (int index : jtLista.getSelectedRows()) {
                paraExcluir.add(lista.get(index));
            }
            int opc = 0;
            opc = JOptionPane.showConfirmDialog(this, "Confirma exclusão de registros?");
            if (opc == 0) {
                for (Time time : paraExcluir) {
                    lista.remove(time);
                }
                lista();
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Selecione pelo menos um time para excluir.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        // TODO add your handling code here:
        JDialog cadastro = new CadastroTime(null, true, lista);
        cadastro.setVisible(true);
        lista();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (jtLista.getSelectedRowCount() == 1) {
            CadastroTime cadastro = new CadastroTime(
                    null, true, lista, jtLista.getSelectedRow());
            cadastro.setVisible(true);
            lista();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione apenas um time da lista.");
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btInserirJogadorElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirJogadorElencoActionPerformed
        if (jtLista.getSelectedRowCount() == 1) {
            ListaJogadores cadastro = new ListaJogadores(
                    null, true, 
            lista.get(jtLista.getSelectedRow()),
            listaj
            );
            cadastro.setVisible(true);
            lista();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Time.");
        }
    }//GEN-LAST:event_btInserirJogadorElencoActionPerformed

    private void btMostrarJogadorElencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarJogadorElencoActionPerformed
        if (jtLista.getSelectedRowCount() == 1) {
            ListaJogadores listajogtime = new ListaJogadores(
                    null, true, 
                    lista.get(
                    jtLista.getSelectedRow()).getPlantel());
            listajogtime.setVisible(true);
            lista();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione apenas um time da lista.");
        }
    }//GEN-LAST:event_btMostrarJogadorElencoActionPerformed

    public void lista() {        
        DefaultTableModel model = (DefaultTableModel) jtLista.getModel();
        model.getDataVector().clear();
        for (Time obj : lista) {
            model.addRow(
                    new Object[]{
                        obj.getNome(),
                        obj.getApelido(),
                        obj.getEscudo()
                    });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ListaTimes dialog = new ListaTimes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btInserirJogadorElenco;
    private javax.swing.JButton btMostrarJogadorElenco;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtLista;
    // End of variables declaration//GEN-END:variables
}
