/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import modelo.Jogador;
import modelo.Jogo;
import modelo.Time;
import java.util.ArrayList;

public class MenuPrincipal extends javax.swing.JFrame {
    ArrayList<Jogador> listaj;
    ArrayList<Time> listat;
    ArrayList<Jogo> listajogo;
    /** Creates new form MenuPrincipal */
    public MenuPrincipal() {
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        }
        initComponents();
        listaj = new ArrayList();
        listat = new ArrayList();
        listajogo = new ArrayList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btManterClientes = new javax.swing.JButton();
        jpImagem = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        miManterJogadores = new javax.swing.JMenuItem();
        miManterTimes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSair = new javax.swing.JMenuItem();
        miMovimentacao = new javax.swing.JMenu();
        miJogadoresTimes = new javax.swing.JMenuItem();
        miAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Jogos de Futebol");
        setExtendedState(6);

        jToolBar1.setRollover(true);

        btManterClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_female.png"))); // NOI18N
        btManterClientes.setToolTipText("Manter Clientes");
        btManterClientes.setFocusable(false);
        btManterClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btManterClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btManterClientes);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jpImagem.setLayout(new java.awt.GridBagLayout());

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sistema.jpg"))); // NOI18N
        lbImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpImagem.add(lbImagem, new java.awt.GridBagConstraints());

        getContentPane().add(jpImagem, java.awt.BorderLayout.CENTER);

        mnArquivo.setText("Arquivo");

        miManterJogadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_female.png"))); // NOI18N
        miManterJogadores.setText("Manter Jogadores");
        miManterJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterJogadoresActionPerformed(evt);
            }
        });
        mnArquivo.add(miManterJogadores);

        miManterTimes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tux.png"))); // NOI18N
        miManterTimes.setText("Manter Times");
        miManterTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManterTimesActionPerformed(evt);
            }
        });
        mnArquivo.add(miManterTimes);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/award_star_bronze_1.png"))); // NOI18N
        jMenu1.setText("Manter Jogos");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/award_star_silver_1.png"))); // NOI18N
        jMenuItem1.setText("Incluir Jogos");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/award_star_silver_2.png"))); // NOI18N
        jMenuItem2.setText("Realizar Jogos");
        jMenu1.add(jMenuItem2);

        mnArquivo.add(jMenu1);
        mnArquivo.add(jSeparator1);

        miSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        miSair.setText("Sair do Sistema");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mnArquivo.add(miSair);

        jMenuBar1.add(mnArquivo);

        miMovimentacao.setText("Movimentação");

        miJogadoresTimes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/briefcase.png"))); // NOI18N
        miJogadoresTimes.setText("Jogadores dos Times");
        miJogadoresTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miJogadoresTimesActionPerformed(evt);
            }
        });
        miMovimentacao.add(miJogadoresTimes);

        jMenuBar1.add(miMovimentacao);

        miAjuda.setText("Ajuda");
        jMenuBar1.add(miAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(2608, 2028));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
        int opc;
        opc = JOptionPane.showConfirmDialog(this,"Sair do Sistema?");
        if (opc == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_miSairActionPerformed

    private void miManterTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterTimesActionPerformed
        // TODO add your handling code here:
       CadastroTime ct = new CadastroTime(this,true,listat);
       ct.setVisible(true);
    }//GEN-LAST:event_miManterTimesActionPerformed

    private void miManterJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManterJogadoresActionPerformed
        CadastroJogador cj = new CadastroJogador(this, true, listaj);
        cj.setVisible(true);
    }//GEN-LAST:event_miManterJogadoresActionPerformed

    private void miJogadoresTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miJogadoresTimesActionPerformed
        // TODO add your handling code here:
        ListaTimes lt = new ListaTimes(this, true, listat, listaj);
        lt.setVisible(true);
    }//GEN-LAST:event_miJogadoresTimesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btManterClientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jpImagem;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JMenu miAjuda;
    private javax.swing.JMenuItem miJogadoresTimes;
    private javax.swing.JMenuItem miManterJogadores;
    private javax.swing.JMenuItem miManterTimes;
    private javax.swing.JMenu miMovimentacao;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenu mnArquivo;
    // End of variables declaration//GEN-END:variables
}
