
package view;

import util.ModeloTabela;
import entidades.Pessoa;
import java.util.ArrayList;
import java.util.List;
import util.GravaArquivoBinario;
import util.LerArquivoBinario;

/**
 *
 * @author Geri
 */
public class ExemploJTable extends javax.swing.JFrame {

    /**
     * Creates new form ExemploJTable
     */
    public ExemploJTable() {
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        }
        initComponents();
        // recuperação das informações do arquivo
        String arq = "c:\\dados\\arqe";
        func = LerArquivoBinario.lerDados(arq);
        modelo = new ModeloTabela(func);
        // modelo sendo atribuído para a tabela criada
        grade.setModel(modelo);
        tfNome.requestFocus();
        // Não permitir que a grade seja editada
        grade.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grade = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btAdiciona = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo de JTable");
        setExtendedState(6);

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Altura:");

        jLabel4.setText("Peso:");

        jLabel5.setText("Sexo:");

        buttonGroup1.add(rbMasc);
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");

        buttonGroup1.add(rbFem);
        rbFem.setText("Feminino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIdade)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPeso)
                    .addComponent(tfAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFem)
                    .addComponent(rbMasc))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(rbMasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbFem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        grade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gradeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(grade);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btAdiciona.setText("Adicionar");
        btAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionaActionPerformed(evt);
            }
        });
        jPanel2.add(btAdiciona);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluir);

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });
        jPanel2.add(btListar);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel2.add(btSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tfNomeActionPerformed

private void btAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionaActionPerformed
// TODO add your handling code here:
    modelo = (ModeloTabela) grade.getModel();
    // Cria o objeto da classe que está sendo trabalhada
    // no momento
    String nome = tfNome.getText();
    try {
        int idade = Integer.parseInt(tfIdade.getText());
        double peso = Double.parseDouble(tfPeso.getText());
        double altura = Double.parseDouble(tfAltura.getText());
        String sexo;
        if (rbMasc.isSelected()) {
            sexo = "Masculino";
        } else {
            sexo = "Feminino";
        }
        if (!nome.equals("")
                && (idade > 0)) {
            Pessoa aux = new Pessoa(nome, idade, altura, peso, sexo);
            modelo.adicionaLinha(aux);
            tfNome.setText("");
            tfIdade.setText("");
            tfPeso.setText("");
            tfAltura.setText("");
            rbMasc.setSelected(true);
            rbFem.setSelected(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Informe os dados!");
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Dados errados: "+e.getMessage());
    }
}//GEN-LAST:event_btAdicionaActionPerformed

private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
// TODO add your handling code here:
    modelo = (ModeloTabela) grade.getModel();
    // mudar para a interface da classe utilizada
    String texto = "Nome:  -  Idade:\n";
    for (int i = 0; i < modelo.getRowCount(); i++) {
        texto += modelo.getValueAt(i, 0) + "  -  "
                + modelo.getValueAt(i, 1) + "\n";
    }
    javax.swing.JOptionPane.showMessageDialog(this,
            texto);
}//GEN-LAST:event_btListarActionPerformed

private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
// TODO add your handling code here:    
    if (grade.getSelectedRow() >= 0) {
        int opc = javax.swing.JOptionPane.showConfirmDialog(
                this, "Excluir registro?");
        if (opc == 0) {
            modelo.removeLinha(grade.getSelectedRow());
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Selecione a linha a ser excluída");
    }
}//GEN-LAST:event_btExcluirActionPerformed

private void gradeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseReleased
// TODO add your handling code here:    
    if (grade.getSelectedRow() >= 0) {
        tfNome.setText((String) modelo.getValueAt(
                grade.getSelectedRow(),
                0));
        tfIdade.setText((String) modelo.getValueAt(
                grade.getSelectedRow(),
                1));
        tfAltura.setText((String) modelo.getValueAt(grade.getSelectedRow(),
                2));
        tfPeso.setText((String) modelo.getValueAt(grade.getSelectedRow(),
                3));
        String sexo = (String) modelo.getValueAt(grade.getSelectedRow(),
                4);
        if (sexo.equals("Masculino")) {
            rbMasc.setSelected(true);
        } else {
            rbFem.setSelected(true);
        }
    }

}//GEN-LAST:event_gradeMouseReleased

private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
    // TODO add your handling code here:
    int opc = javax.swing.JOptionPane.showConfirmDialog(
            this, "Sair do sistema?");
    if (opc == 0) {
            // trocar o vetor func pelo vetor que está
        // sendo utilizado no 
        String arq = "c:\\dados\\arqe";
        String dir = "c:\\dados";
        GravaArquivoBinario.gravaArquivoBinario(func, arq, dir);
        System.exit(0);
    }
}//GEN-LAST:event_btSairActionPerformed

private void gradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseClicked
    // TODO add your handling code here:    
}//GEN-LAST:event_gradeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExemploJTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdiciona;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    // End of variables declaration//GEN-END:variables
    // definição de um vetor dinâmico
    private List<Pessoa> func = new ArrayList();
    ModeloTabela modelo;
}
